type: array
items:
  type: object
  properties:
    repositories:
      description: Array of repositories on which the labels and milestones should be synchronized.
      type: array
      items:
        type: string
    milestones:
      description: Array of milestones that should be synchronized.
      type: array
      items:
        type: object
        properties:
          title:
            description: The title of the milestone.
            type: string
          previousTitles:
            description: Array of titles this milestone had before. We will try to rename milestones found here to title instead of creating a new one.
            type: array
            items:
              type: string
          state:
            description: The state of the milestone. Either open, closed or absent.
            enum:
              - open
              - closed
              - absent
            default: open
          description:
            description: A description of the milestone.
            type: string
          due_on:
            description: The milestone due date. This is a timestamp in ISO 8601 format.
            type: string
            format: date-time
        required:
          - title
    labels:
      description: Array of labels that should be synchronized.
      type: array
      items:
        type: object
        properties:
          name:
            description: The name of the label.
            type: string
          color:
            description: A 6 character hex code, without the leading \#, identifying the color.
            type: string
          previousNames:
            description: Array of names this label had before. The new label will be added to issues with any of these and the previous labels will then be deleted.
            type: array
            items:
              type: string
          state:
            description: Can be present or absent.
            enum:
              - present
              - absent
            default: present
        required:
          - name
          - color
